#!/bin/bash
sudo apt update

git clone https://github.com/carlosdizx/......
# shellcheck disable=SC2164
cd .......

cat <<EOF > .env
OPEN_AI_API_KEY=sk...
DB_SERVER=....
DB_DATABASE=...
DB_USERNAME=...
DB_PASSWORD=...
DB_PORT=...
EOF

pip install -r requirements.txt

nohup streamlit run /home/ec2-user/main.py &
